### ISSUE TITLE
Compiling 'master/intl/osdep.c' breaks

### ISSUE THREAD

**Issue by rdpe** [bitwiseworks/gcc-os2#24]
It seems gcc automatically enables the `__EMX__` macro.
The `osdep.c` source tries to conditionally include `os2compat.c`, which is not there.
Could not find `os2compat.c` in Paul's old repo either.
...?

**Comment by dmik** [comment]
Something is wrong with your configure flags or env or such. No code from `intl` is built here in our RPM env with configure flags from the instructions. Maybe you need to install `gettext-devel` so that configure picks it up instead of trying to build its own copy. And check what configure says for you about gettext. Here it says this:
```
checking whether included gettext is requested... no
checking for GNU gettext in libc... yes
checking for GNU gettext in libintl... yes
checking whether to use NLS... yes
checking where the gettext function comes from... external libintl
checking how to link with libintl... -lintl
``` 
And GCC binaries link to `intl8.dll` which is part of the `gettext-libs` RPM.

**Comment by rdpe** [comment]
Ahh, indeed installing `gettext-devel` solved the issue.
(It was not installed)

Now, of course one would expect that anyone trying to build a mammoth like `gcc-os2`
would first upgrade their system to the latest, but I would also argue that installing a
fresh `ArcaOS v5.0.4`, cloning the repo and pasting the `yum` line should work.

For that to work, `gettext-devel`, `os2-rpm` and `gawk` should be in the `yum` line too. (`os2-rpm` to fix the `getbootdrive` issue)

Anyway, I'm now more in the direction of #12, which was the spark for trying to build.
Thanks!

**Comment by dmik** [comment]
Ok, closing this.
