### ISSUE TITLE
stdcpp6 update breaks DOSBox.

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/gcc-os2#28]
As discussed on os2world, https://www.os2world.com/forum/index.php/topic,2455.0.html it appears that a stdcpp6 update broke DOSBox, or perhaps the SDL file required by DOSBox.
```
[C:\Programs\DOSBOX]dosbox
DOSBox version SVN
Copyright 2002-2019 DOSBox Team, published under GNU GPL.
---

Killed by SIGSEGV
pid=0x00c7 ppid=0x00c4 tid=0x0001 slot=0x00db pri=0x0200 mc=0x0001 ps=0x0010
C:\PROGRAMS\DOSBOX\DOSBOX.EXE
STDCPP6 0:0001b26d
cs:eip=005b:1e24b26d      ss:esp=0053:0289fb20      ebp=0289fb38
 ds=0053      es=0053      fs=150b      gs=0000     efl=00012287
eax=0289fe2c ebx=00000000 ecx=199b5f00 edx=199b5f00 edi=0289feb8 esi=0289fb5c
Process dumping was disabled, use DUMPPROC / PROCDUMP to enable it.
```
I don't use DOSBox and suggested users file this report but they didn't.
In this case, as the OS/2 patches were committed upstream, I rebuilt DOSBox. But if one program gets broken by an update, others may well also break and the source isn't always available.

**Comment by SilvanScherrer** [comment]
This is the 2nd app we know which had issues with the new stdcpp6. But to be honest we don't have the Manpower to debug that. And as a rebuild runs here we think all is fine. 
We suspect some issues with the old stdcpp which got fixed in gcc9 and thats more than hard to debug.
I close this issue as non fixable. If one thinks otherwise please reopen.
